modLoader="javafml"
loaderVersion="[39,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"
logoFile="icon.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
credits=""
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="flytre_lib"
mandatory=true
versionRange="[${lib_version},)"
ordering="NONE"
side="BOTH"